# Generated by verify_validation_subset.py
reinitialize
set retain_order, 1
set dash_width, 2.5
bg_color white
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/P24941__2cch__A__target-160__ctx-160__mode-joint/input/reference_phospho.cif", case_cdk2_2cch_t160_ref
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/P24941__2cch__A__target-160__ctx-160__mode-joint/input/stripped_input.cif", case_cdk2_2cch_t160_stripped
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/P24941__2cch__A__target-160__ctx-160__mode-joint/stage0/structure_s0.cif", case_cdk2_2cch_t160_s0
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/P24941__2cch__A__target-160__ctx-160__mode-joint/stage1/structure_s1.cif", case_cdk2_2cch_t160_s1
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/P24941__2cch__A__target-160__ctx-160__mode-joint/stage2/structure_s2.cif", case_cdk2_2cch_t160_s2
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/P24941__2cch__A__target-160__ctx-160__mode-joint/stage3/phosphoFill1.cif", case_cdk2_2cch_t160_top1
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/P24941__2cch__A__target-160__ctx-160__mode-joint/stage3/phosphoFill2.cif", case_cdk2_2cch_t160_top2
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/P24941__2cch__A__target-160__ctx-160__mode-joint/stage3/phosphoFill3.cif", case_cdk2_2cch_t160_top3
hide everything, case_cdk2_2cch_t160_*
show sticks, case_cdk2_2cch_t160_* and chain A and resi 160
color gray70, case_cdk2_2cch_t160_ref
color cyan, case_cdk2_2cch_t160_s0
color marine, case_cdk2_2cch_t160_s1
color orange, case_cdk2_2cch_t160_s2
color tv_blue, case_cdk2_2cch_t160_top1
color violet, case_cdk2_2cch_t160_top2
color salmon, case_cdk2_2cch_t160_top3
disable case_cdk2_2cch_t160_*
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/P24941__4eoj__A__target-160__ctx-160__mode-joint/input/reference_phospho.cif", case_cdk2_4eoj_t160_ref
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/P24941__4eoj__A__target-160__ctx-160__mode-joint/input/stripped_input.cif", case_cdk2_4eoj_t160_stripped
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/P24941__4eoj__A__target-160__ctx-160__mode-joint/stage0/structure_s0.cif", case_cdk2_4eoj_t160_s0
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/P24941__4eoj__A__target-160__ctx-160__mode-joint/stage1/structure_s1.cif", case_cdk2_4eoj_t160_s1
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/P24941__4eoj__A__target-160__ctx-160__mode-joint/stage2/structure_s2.cif", case_cdk2_4eoj_t160_s2
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/P24941__4eoj__A__target-160__ctx-160__mode-joint/stage3/phosphoFill1.cif", case_cdk2_4eoj_t160_top1
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/P24941__4eoj__A__target-160__ctx-160__mode-joint/stage3/phosphoFill2.cif", case_cdk2_4eoj_t160_top2
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/P24941__4eoj__A__target-160__ctx-160__mode-joint/stage3/phosphoFill3.cif", case_cdk2_4eoj_t160_top3
hide everything, case_cdk2_4eoj_t160_*
show sticks, case_cdk2_4eoj_t160_* and chain A and resi 160
color gray70, case_cdk2_4eoj_t160_ref
color cyan, case_cdk2_4eoj_t160_s0
color marine, case_cdk2_4eoj_t160_s1
color orange, case_cdk2_4eoj_t160_s2
color tv_blue, case_cdk2_4eoj_t160_top1
color violet, case_cdk2_4eoj_t160_top2
color salmon, case_cdk2_4eoj_t160_top3
disable case_cdk2_4eoj_t160_*
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/P28482__4iza__A__target-185__ctx-185__mode-joint/input/reference_phospho.cif", case_erk2_4iza_t185_ref
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/P28482__4iza__A__target-185__ctx-185__mode-joint/input/stripped_input.cif", case_erk2_4iza_t185_stripped
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/P28482__4iza__A__target-185__ctx-185__mode-joint/stage0/structure_s0.cif", case_erk2_4iza_t185_s0
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/P28482__4iza__A__target-185__ctx-185__mode-joint/stage1/structure_s1.cif", case_erk2_4iza_t185_s1
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/P28482__4iza__A__target-185__ctx-185__mode-joint/stage2/structure_s2.cif", case_erk2_4iza_t185_s2
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/P28482__4iza__A__target-185__ctx-185__mode-joint/stage3/phosphoFill1.cif", case_erk2_4iza_t185_top1
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/P28482__4iza__A__target-185__ctx-185__mode-joint/stage3/phosphoFill2.cif", case_erk2_4iza_t185_top2
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/P28482__4iza__A__target-185__ctx-185__mode-joint/stage3/phosphoFill3.cif", case_erk2_4iza_t185_top3
hide everything, case_erk2_4iza_t185_*
show sticks, case_erk2_4iza_t185_* and chain A and resi 185
color gray70, case_erk2_4iza_t185_ref
color cyan, case_erk2_4iza_t185_s0
color marine, case_erk2_4iza_t185_s1
color orange, case_erk2_4iza_t185_s2
color tv_blue, case_erk2_4iza_t185_top1
color violet, case_erk2_4iza_t185_top2
color salmon, case_erk2_4iza_t185_top3
disable case_erk2_4iza_t185_*
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/P28482__5v62__A__target-185__ctx-185__mode-joint/input/reference_phospho.cif", case_erk2_5v62_t185_ref
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/P28482__5v62__A__target-185__ctx-185__mode-joint/input/stripped_input.cif", case_erk2_5v62_t185_stripped
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/P28482__5v62__A__target-185__ctx-185__mode-joint/stage0/structure_s0.cif", case_erk2_5v62_t185_s0
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/P28482__5v62__A__target-185__ctx-185__mode-joint/stage1/structure_s1.cif", case_erk2_5v62_t185_s1
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/P28482__5v62__A__target-185__ctx-185__mode-joint/stage2/structure_s2.cif", case_erk2_5v62_t185_s2
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/P28482__5v62__A__target-185__ctx-185__mode-joint/stage3/phosphoFill1.cif", case_erk2_5v62_t185_top1
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/P28482__5v62__A__target-185__ctx-185__mode-joint/stage3/phosphoFill2.cif", case_erk2_5v62_t185_top2
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/P28482__5v62__A__target-185__ctx-185__mode-joint/stage3/phosphoFill3.cif", case_erk2_5v62_t185_top3
hide everything, case_erk2_5v62_t185_*
show sticks, case_erk2_5v62_t185_* and chain A and resi 185
color gray70, case_erk2_5v62_t185_ref
color cyan, case_erk2_5v62_t185_s0
color marine, case_erk2_5v62_t185_s1
color orange, case_erk2_5v62_t185_s2
color tv_blue, case_erk2_5v62_t185_top1
color violet, case_erk2_5v62_t185_top2
color salmon, case_erk2_5v62_t185_top3
disable case_erk2_5v62_t185_*
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/O14965__4bn1__A__target-287_288__ctx-287_288__mode-joint/input/reference_phospho.cif", control_tpo_4bn1_multi_ref
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/O14965__4bn1__A__target-287_288__ctx-287_288__mode-joint/input/stripped_input.cif", control_tpo_4bn1_multi_stripped
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/O14965__4bn1__A__target-287_288__ctx-287_288__mode-joint/stage0/structure_s0.cif", control_tpo_4bn1_multi_s0
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/O14965__4bn1__A__target-287_288__ctx-287_288__mode-joint/stage1/structure_s1.cif", control_tpo_4bn1_multi_s1
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/O14965__4bn1__A__target-287_288__ctx-287_288__mode-joint/stage2/structure_s2.cif", control_tpo_4bn1_multi_s2
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/O14965__4bn1__A__target-287_288__ctx-287_288__mode-joint/stage3/phosphoFill1.cif", control_tpo_4bn1_multi_top1
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/O14965__4bn1__A__target-287_288__ctx-287_288__mode-joint/stage3/phosphoFill2.cif", control_tpo_4bn1_multi_top2
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/TPO/mode-joint__w-0.0__pack-0.2/O14965__4bn1__A__target-287_288__ctx-287_288__mode-joint/stage3/phosphoFill3.cif", control_tpo_4bn1_multi_top3
hide everything, control_tpo_4bn1_multi_*
show sticks, control_tpo_4bn1_multi_* and chain A and resi 287+288
color gray70, control_tpo_4bn1_multi_ref
color cyan, control_tpo_4bn1_multi_s0
color marine, control_tpo_4bn1_multi_s1
color orange, control_tpo_4bn1_multi_s2
color tv_blue, control_tpo_4bn1_multi_top1
color violet, control_tpo_4bn1_multi_top2
color salmon, control_tpo_4bn1_multi_top3
disable control_tpo_4bn1_multi_*
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/P11309__8r27__A__target-261__ctx-261__mode-joint/input/reference_phospho.cif", control_sep_8r27_seed_match_ref
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/P11309__8r27__A__target-261__ctx-261__mode-joint/input/stripped_input.cif", control_sep_8r27_seed_match_stripped
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/P11309__8r27__A__target-261__ctx-261__mode-joint/stage0/structure_s0.cif", control_sep_8r27_seed_match_s0
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/P11309__8r27__A__target-261__ctx-261__mode-joint/stage1/structure_s1.cif", control_sep_8r27_seed_match_s1
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/P11309__8r27__A__target-261__ctx-261__mode-joint/stage2/structure_s2.cif", control_sep_8r27_seed_match_s2
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/P11309__8r27__A__target-261__ctx-261__mode-joint/stage3/phosphoFill1.cif", control_sep_8r27_seed_match_top1
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/P11309__8r27__A__target-261__ctx-261__mode-joint/stage3/phosphoFill2.cif", control_sep_8r27_seed_match_top2
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/P11309__8r27__A__target-261__ctx-261__mode-joint/stage3/phosphoFill3.cif", control_sep_8r27_seed_match_top3
hide everything, control_sep_8r27_seed_match_*
show sticks, control_sep_8r27_seed_match_* and chain A and resi 261
color gray70, control_sep_8r27_seed_match_ref
color cyan, control_sep_8r27_seed_match_s0
color marine, control_sep_8r27_seed_match_s1
color orange, control_sep_8r27_seed_match_s2
color tv_blue, control_sep_8r27_seed_match_top1
color violet, control_sep_8r27_seed_match_top2
color salmon, control_sep_8r27_seed_match_top3
disable control_sep_8r27_seed_match_*
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/O15530__1uu3__A__target-241__ctx-241__mode-joint/input/reference_phospho.cif", control_sep_1uu3_scan_rescue_ref
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/O15530__1uu3__A__target-241__ctx-241__mode-joint/input/stripped_input.cif", control_sep_1uu3_scan_rescue_stripped
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/O15530__1uu3__A__target-241__ctx-241__mode-joint/stage0/structure_s0.cif", control_sep_1uu3_scan_rescue_s0
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/O15530__1uu3__A__target-241__ctx-241__mode-joint/stage1/structure_s1.cif", control_sep_1uu3_scan_rescue_s1
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/O15530__1uu3__A__target-241__ctx-241__mode-joint/stage2/structure_s2.cif", control_sep_1uu3_scan_rescue_s2
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/O15530__1uu3__A__target-241__ctx-241__mode-joint/stage3/phosphoFill1.cif", control_sep_1uu3_scan_rescue_top1
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/O15530__1uu3__A__target-241__ctx-241__mode-joint/stage3/phosphoFill2.cif", control_sep_1uu3_scan_rescue_top2
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/O15530__1uu3__A__target-241__ctx-241__mode-joint/stage3/phosphoFill3.cif", control_sep_1uu3_scan_rescue_top3
hide everything, control_sep_1uu3_scan_rescue_*
show sticks, control_sep_1uu3_scan_rescue_* and chain A and resi 241
color gray70, control_sep_1uu3_scan_rescue_ref
color cyan, control_sep_1uu3_scan_rescue_s0
color marine, control_sep_1uu3_scan_rescue_s1
color orange, control_sep_1uu3_scan_rescue_s2
color tv_blue, control_sep_1uu3_scan_rescue_top1
color violet, control_sep_1uu3_scan_rescue_top2
color salmon, control_sep_1uu3_scan_rescue_top3
disable control_sep_1uu3_scan_rescue_*
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/P32356__5n6n__C__target-60_83__ctx-60_83__mode-joint/input/reference_phospho.cif", control_sep_5n6n_multi_ref
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/P32356__5n6n__C__target-60_83__ctx-60_83__mode-joint/input/stripped_input.cif", control_sep_5n6n_multi_stripped
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/P32356__5n6n__C__target-60_83__ctx-60_83__mode-joint/stage0/structure_s0.cif", control_sep_5n6n_multi_s0
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/P32356__5n6n__C__target-60_83__ctx-60_83__mode-joint/stage1/structure_s1.cif", control_sep_5n6n_multi_s1
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/P32356__5n6n__C__target-60_83__ctx-60_83__mode-joint/stage2/structure_s2.cif", control_sep_5n6n_multi_s2
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/P32356__5n6n__C__target-60_83__ctx-60_83__mode-joint/stage3/phosphoFill1.cif", control_sep_5n6n_multi_top1
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/P32356__5n6n__C__target-60_83__ctx-60_83__mode-joint/stage3/phosphoFill2.cif", control_sep_5n6n_multi_top2
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/P32356__5n6n__C__target-60_83__ctx-60_83__mode-joint/stage3/phosphoFill3.cif", control_sep_5n6n_multi_top3
hide everything, control_sep_5n6n_multi_*
show sticks, control_sep_5n6n_multi_* and chain C and resi 60+83
color gray70, control_sep_5n6n_multi_ref
color cyan, control_sep_5n6n_multi_s0
color marine, control_sep_5n6n_multi_s1
color orange, control_sep_5n6n_multi_s2
color tv_blue, control_sep_5n6n_multi_top1
color violet, control_sep_5n6n_multi_top2
color salmon, control_sep_5n6n_multi_top3
disable control_sep_5n6n_multi_*
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/P26361__1r0z__C__target-422_659_660_670__ctx-422_659_660_670__mode-joint/input/reference_phospho.cif", regression_sep_1r0z_chain_c_ref
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/P26361__1r0z__C__target-422_659_660_670__ctx-422_659_660_670__mode-joint/input/stripped_input.cif", regression_sep_1r0z_chain_c_stripped
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/P26361__1r0z__C__target-422_659_660_670__ctx-422_659_660_670__mode-joint/stage0/structure_s0.cif", regression_sep_1r0z_chain_c_s0
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/P26361__1r0z__C__target-422_659_660_670__ctx-422_659_660_670__mode-joint/stage1/structure_s1.cif", regression_sep_1r0z_chain_c_s1
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/P26361__1r0z__C__target-422_659_660_670__ctx-422_659_660_670__mode-joint/stage2/structure_s2.cif", regression_sep_1r0z_chain_c_s2
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/P26361__1r0z__C__target-422_659_660_670__ctx-422_659_660_670__mode-joint/stage3/phosphoFill1.cif", regression_sep_1r0z_chain_c_top1
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/P26361__1r0z__C__target-422_659_660_670__ctx-422_659_660_670__mode-joint/stage3/phosphoFill2.cif", regression_sep_1r0z_chain_c_top2
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/P26361__1r0z__C__target-422_659_660_670__ctx-422_659_660_670__mode-joint/stage3/phosphoFill3.cif", regression_sep_1r0z_chain_c_top3
hide everything, regression_sep_1r0z_chain_c_*
show sticks, regression_sep_1r0z_chain_c_* and chain C and resi 422+660+659+670
color gray70, regression_sep_1r0z_chain_c_ref
color cyan, regression_sep_1r0z_chain_c_s0
color marine, regression_sep_1r0z_chain_c_s1
color orange, regression_sep_1r0z_chain_c_s2
color tv_blue, regression_sep_1r0z_chain_c_top1
color violet, regression_sep_1r0z_chain_c_top2
color salmon, regression_sep_1r0z_chain_c_top3
disable regression_sep_1r0z_chain_c_*
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/P26361__1r0z__D__target-659_660_670__ctx-659_660_670__mode-joint/input/reference_phospho.cif", regression_sep_1r0z_chain_d_ref
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/P26361__1r0z__D__target-659_660_670__ctx-659_660_670__mode-joint/input/stripped_input.cif", regression_sep_1r0z_chain_d_stripped
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/P26361__1r0z__D__target-659_660_670__ctx-659_660_670__mode-joint/stage0/structure_s0.cif", regression_sep_1r0z_chain_d_s0
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/P26361__1r0z__D__target-659_660_670__ctx-659_660_670__mode-joint/stage1/structure_s1.cif", regression_sep_1r0z_chain_d_s1
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/P26361__1r0z__D__target-659_660_670__ctx-659_660_670__mode-joint/stage2/structure_s2.cif", regression_sep_1r0z_chain_d_s2
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/P26361__1r0z__D__target-659_660_670__ctx-659_660_670__mode-joint/stage3/phosphoFill1.cif", regression_sep_1r0z_chain_d_top1
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/P26361__1r0z__D__target-659_660_670__ctx-659_660_670__mode-joint/stage3/phosphoFill2.cif", regression_sep_1r0z_chain_d_top2
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/SEP/mode-joint__w-0.0__pack-0.2/P26361__1r0z__D__target-659_660_670__ctx-659_660_670__mode-joint/stage3/phosphoFill3.cif", regression_sep_1r0z_chain_d_top3
hide everything, regression_sep_1r0z_chain_d_*
show sticks, regression_sep_1r0z_chain_d_* and chain D and resi 660+670+659
color gray70, regression_sep_1r0z_chain_d_ref
color cyan, regression_sep_1r0z_chain_d_s0
color marine, regression_sep_1r0z_chain_d_s1
color orange, regression_sep_1r0z_chain_d_s2
color tv_blue, regression_sep_1r0z_chain_d_top1
color violet, regression_sep_1r0z_chain_d_top2
color salmon, regression_sep_1r0z_chain_d_top3
disable regression_sep_1r0z_chain_d_*
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/PTR/mode-joint__w-0.0__pack-0.2/P28482__4iza__A__target-187__ctx-187__mode-joint/input/reference_phospho.cif", case_erk2_4iza_y187_ref
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/PTR/mode-joint__w-0.0__pack-0.2/P28482__4iza__A__target-187__ctx-187__mode-joint/input/stripped_input.cif", case_erk2_4iza_y187_stripped
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/PTR/mode-joint__w-0.0__pack-0.2/P28482__4iza__A__target-187__ctx-187__mode-joint/stage0/structure_s0.cif", case_erk2_4iza_y187_s0
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/PTR/mode-joint__w-0.0__pack-0.2/P28482__4iza__A__target-187__ctx-187__mode-joint/stage1/structure_s1.cif", case_erk2_4iza_y187_s1
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/PTR/mode-joint__w-0.0__pack-0.2/P28482__4iza__A__target-187__ctx-187__mode-joint/stage2/structure_s2.cif", case_erk2_4iza_y187_s2
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/PTR/mode-joint__w-0.0__pack-0.2/P28482__4iza__A__target-187__ctx-187__mode-joint/stage3/phosphoFill1.cif", case_erk2_4iza_y187_top1
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/PTR/mode-joint__w-0.0__pack-0.2/P28482__4iza__A__target-187__ctx-187__mode-joint/stage3/phosphoFill2.cif", case_erk2_4iza_y187_top2
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/PTR/mode-joint__w-0.0__pack-0.2/P28482__4iza__A__target-187__ctx-187__mode-joint/stage3/phosphoFill3.cif", case_erk2_4iza_y187_top3
hide everything, case_erk2_4iza_y187_*
show sticks, case_erk2_4iza_y187_* and chain A and resi 187
color gray70, case_erk2_4iza_y187_ref
color cyan, case_erk2_4iza_y187_s0
color marine, case_erk2_4iza_y187_s1
color orange, case_erk2_4iza_y187_s2
color tv_blue, case_erk2_4iza_y187_top1
color violet, case_erk2_4iza_y187_top2
color salmon, case_erk2_4iza_y187_top3
disable case_erk2_4iza_y187_*
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/PTR/mode-joint__w-0.0__pack-0.2/P28482__5v62__A__target-187__ctx-187__mode-joint/input/reference_phospho.cif", case_erk2_5v62_y187_ref
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/PTR/mode-joint__w-0.0__pack-0.2/P28482__5v62__A__target-187__ctx-187__mode-joint/input/stripped_input.cif", case_erk2_5v62_y187_stripped
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/PTR/mode-joint__w-0.0__pack-0.2/P28482__5v62__A__target-187__ctx-187__mode-joint/stage0/structure_s0.cif", case_erk2_5v62_y187_s0
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/PTR/mode-joint__w-0.0__pack-0.2/P28482__5v62__A__target-187__ctx-187__mode-joint/stage1/structure_s1.cif", case_erk2_5v62_y187_s1
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/PTR/mode-joint__w-0.0__pack-0.2/P28482__5v62__A__target-187__ctx-187__mode-joint/stage2/structure_s2.cif", case_erk2_5v62_y187_s2
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/PTR/mode-joint__w-0.0__pack-0.2/P28482__5v62__A__target-187__ctx-187__mode-joint/stage3/phosphoFill1.cif", case_erk2_5v62_y187_top1
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/PTR/mode-joint__w-0.0__pack-0.2/P28482__5v62__A__target-187__ctx-187__mode-joint/stage3/phosphoFill2.cif", case_erk2_5v62_y187_top2
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/PTR/mode-joint__w-0.0__pack-0.2/P28482__5v62__A__target-187__ctx-187__mode-joint/stage3/phosphoFill3.cif", case_erk2_5v62_y187_top3
hide everything, case_erk2_5v62_y187_*
show sticks, case_erk2_5v62_y187_* and chain A and resi 187
color gray70, case_erk2_5v62_y187_ref
color cyan, case_erk2_5v62_y187_s0
color marine, case_erk2_5v62_y187_s1
color orange, case_erk2_5v62_y187_s2
color tv_blue, case_erk2_5v62_y187_top1
color violet, case_erk2_5v62_y187_top2
color salmon, case_erk2_5v62_y187_top3
disable case_erk2_5v62_y187_*
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/PTR/mode-joint__w-0.0__pack-0.2/Q00944__2j0l__A__target-576_577__ctx-576_577__mode-joint/input/reference_phospho.cif", control_ptr_2j0l_multi_ref
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/PTR/mode-joint__w-0.0__pack-0.2/Q00944__2j0l__A__target-576_577__ctx-576_577__mode-joint/input/stripped_input.cif", control_ptr_2j0l_multi_stripped
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/PTR/mode-joint__w-0.0__pack-0.2/Q00944__2j0l__A__target-576_577__ctx-576_577__mode-joint/stage0/structure_s0.cif", control_ptr_2j0l_multi_s0
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/PTR/mode-joint__w-0.0__pack-0.2/Q00944__2j0l__A__target-576_577__ctx-576_577__mode-joint/stage1/structure_s1.cif", control_ptr_2j0l_multi_s1
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/PTR/mode-joint__w-0.0__pack-0.2/Q00944__2j0l__A__target-576_577__ctx-576_577__mode-joint/stage2/structure_s2.cif", control_ptr_2j0l_multi_s2
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/PTR/mode-joint__w-0.0__pack-0.2/Q00944__2j0l__A__target-576_577__ctx-576_577__mode-joint/stage3/phosphoFill1.cif", control_ptr_2j0l_multi_top1
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/PTR/mode-joint__w-0.0__pack-0.2/Q00944__2j0l__A__target-576_577__ctx-576_577__mode-joint/stage3/phosphoFill2.cif", control_ptr_2j0l_multi_top2
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/PTR/mode-joint__w-0.0__pack-0.2/Q00944__2j0l__A__target-576_577__ctx-576_577__mode-joint/stage3/phosphoFill3.cif", control_ptr_2j0l_multi_top3
hide everything, control_ptr_2j0l_multi_*
show sticks, control_ptr_2j0l_multi_* and chain A and resi 576+577
color gray70, control_ptr_2j0l_multi_ref
color cyan, control_ptr_2j0l_multi_s0
color marine, control_ptr_2j0l_multi_s1
color orange, control_ptr_2j0l_multi_s2
color tv_blue, control_ptr_2j0l_multi_top1
color violet, control_ptr_2j0l_multi_top2
color salmon, control_ptr_2j0l_multi_top3
disable control_ptr_2j0l_multi_*
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/PTR/mode-joint__w-0.0__pack-0.2/P08069__2zm3__A__target-1161_1165_1166__ctx-1161_1165_1166__mode-joint/input/reference_phospho.cif", regression_ptr_2zm3_missing_ref_ref
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/PTR/mode-joint__w-0.0__pack-0.2/P08069__2zm3__A__target-1161_1165_1166__ctx-1161_1165_1166__mode-joint/input/stripped_input.cif", regression_ptr_2zm3_missing_ref_stripped
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/PTR/mode-joint__w-0.0__pack-0.2/P08069__2zm3__A__target-1161_1165_1166__ctx-1161_1165_1166__mode-joint/stage0/structure_s0.cif", regression_ptr_2zm3_missing_ref_s0
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/PTR/mode-joint__w-0.0__pack-0.2/P08069__2zm3__A__target-1161_1165_1166__ctx-1161_1165_1166__mode-joint/stage1/structure_s1.cif", regression_ptr_2zm3_missing_ref_s1
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/PTR/mode-joint__w-0.0__pack-0.2/P08069__2zm3__A__target-1161_1165_1166__ctx-1161_1165_1166__mode-joint/stage2/structure_s2.cif", regression_ptr_2zm3_missing_ref_s2
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/PTR/mode-joint__w-0.0__pack-0.2/P08069__2zm3__A__target-1161_1165_1166__ctx-1161_1165_1166__mode-joint/stage3/phosphoFill1.cif", regression_ptr_2zm3_missing_ref_top1
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/PTR/mode-joint__w-0.0__pack-0.2/P08069__2zm3__A__target-1161_1165_1166__ctx-1161_1165_1166__mode-joint/stage3/phosphoFill2.cif", regression_ptr_2zm3_missing_ref_top2
load "/mnt/c/Users/drpat/OneDrive - UGent/Desktop/PD/Phospho-fill/Benchmarkv2/PhosphoFill-gihub/Benchmark/validation_structure_subset/outputs/archives/PTR/mode-joint__w-0.0__pack-0.2/P08069__2zm3__A__target-1161_1165_1166__ctx-1161_1165_1166__mode-joint/stage3/phosphoFill3.cif", regression_ptr_2zm3_missing_ref_top3
hide everything, regression_ptr_2zm3_missing_ref_*
show sticks, regression_ptr_2zm3_missing_ref_* and chain A and resi 1165+1166+1161
color gray70, regression_ptr_2zm3_missing_ref_ref
color cyan, regression_ptr_2zm3_missing_ref_s0
color marine, regression_ptr_2zm3_missing_ref_s1
color orange, regression_ptr_2zm3_missing_ref_s2
color tv_blue, regression_ptr_2zm3_missing_ref_top1
color violet, regression_ptr_2zm3_missing_ref_top2
color salmon, regression_ptr_2zm3_missing_ref_top3
disable regression_ptr_2zm3_missing_ref_*
# Enable one case with: enable <case_id>_*
zoom
